spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    format_sql: true
    highlight_sql: true
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      springframework:
        security: trace
server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: changeit
